name: webscrape
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py38h1e8a9f7_2
  - astroid=2.4.2=py38h32f6830_1
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - automat=20.2.0=py_0
  - autopep8=1.5.4=pyh9f0ad1d_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bcrypt=3.2.0=py38h1e8a9f7_1
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py38hab1e662_1001
  - ca-certificates=2020.11.8=h5b45459_0
  - certifi=2020.6.20=py38h9bdc248_2
  - cffi=1.14.3=py38h0e640b1_1
  - chardet=3.0.4=py38h9bdc248_1008
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - console_shortcut=0.1.1=4
  - constantly=15.1.0=py_0
  - cryptography=3.2.1=py38hd8c33c5_0
  - cssselect=1.1.0=py_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20200713=pyh9f0ad1d_0
  - docutils=0.16=py38h9bdc248_2
  - entrypoints=0.3=py38h32f6830_1002
  - flake8=3.8.4=py_0
  - flask=1.1.2=pyh9f0ad1d_0
  - freetype=2.10.4=h546665d_0
  - future=0.18.2=py38h32f6830_2
  - helpdev=0.7.1=pyhd8ed1ab_0
  - hyperlink=20.0.1=pyh9f0ad1d_0
  - icu=67.1=h33f27b4_0
  - idna=2.10=pyh9f0ad1d_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - incremental=17.5.0=py_0
  - intel-openmp=2020.3=h57928b3_311
  - intervaltree=3.0.2=py_0
  - ipykernel=5.3.4=py38h7b7c402_1
  - ipython=7.19.0=py38hc5df569_0
  - ipython_genutils=0.2.0=py_1
  - isort=5.6.4=py_0
  - itemadapter=0.1.1=py_0
  - itemloaders=1.0.3=py_0
  - itsdangerous=1.1.0=py_0
  - jedi=0.17.1=py38h32f6830_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py38h32f6830_2
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - keyring=21.4.0=py38h32f6830_2
  - kiwisolver=1.3.1=py38hbd9d945_0
  - lazy-object-proxy=1.4.3=py38h1e8a9f7_2
  - libblas=3.9.0=3_hd5c7e75_netlib
  - libcblas=3.9.0=3_hd5c7e75_netlib
  - libclang=10.0.1=default_hf44288c_1
  - libiconv=1.16=he774522_0
  - liblapack=3.9.0=3_hd5c7e75_netlib
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h62dcd97_1
  - libspatialindex=1.9.3=he025d50_3
  - libtiff=4.1.0=hc10be44_6
  - libxml2=2.9.10=h1006b36_2
  - libxslt=1.1.33=h579f668_1
  - lxml=4.6.1=py38he3d0fc9_0
  - lz4-c=1.9.2=h62dcd97_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38hab1e662_2
  - matplotlib=3.3.2=py38haa244fe_1
  - matplotlib-base=3.3.2=py38h34ddff4_1
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py38h1e8a9f7_1002
  - mkl=2020.4=hb70f87d_311
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h32f6830_2
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.2=pyhd8ed1ab_0
  - notebook=6.1.5=py38haa244fe_0
  - numpy=1.19.4=py38h0cc643e_1
  - numpydoc=1.1.0=py_1
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.4=py38h4c96930_0
  - pandoc=2.11.0.4=hf4a77e7_0
  - pandocfilters=1.4.2=py_1
  - paramiko=2.7.2=pyh9f0ad1d_0
  - parsel=1.6.0=py_0
  - parso=0.7.0=pyh9f0ad1d_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.1=py38hd8d9125_0
  - pip=20.2.4=py_0
  - pluggy=0.13.1=py38h9bdc248_3
  - powershell_shortcut=0.0.1=3
  - praw=7.0.0=py_0
  - prawcore=1.3.0=pyh9f0ad1d_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.8=py_0
  - protego=0.1.16=py_0
  - psutil=5.7.3=py38hab1e662_0
  - ptyprocess=0.6.0=py_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydispatcher=2.0.5=py_1
  - pydocstyle=5.1.1=py_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.7.2=py_0
  - pyhamcrest=2.0.2=py_0
  - pylint=2.6.0=py38h32f6830_1
  - pynacl=1.4.0=py38hd4486f3_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h7ae7562_4
  - pyrsistent=0.17.3=py38h1e8a9f7_1
  - pysocks=1.7.1=py38h9bdc248_2
  - python=3.8.6=h60c2a47_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.4.0=pyh9f0ad1d_0
  - python-language-server=0.36.0=pyhd8ed1ab_0
  - python_abi=3.8=1_cp38
  - pytz=2020.4=pyhd8ed1ab_0
  - pywin32=228=py38h1e8a9f7_0
  - pywin32-ctypes=0.2.0=py38h32f6830_1002
  - pywinpty=0.5.7=py38h32f6830_1
  - pyyaml=5.3.1=py38hab1e662_1
  - pyzmq=19.0.2=py38h77b9d75_2
  - qdarkstyle=2.8.1=pyhd8ed1ab_2
  - qt=5.12.9=hb2cf2c5_0
  - qtawesome=1.0.1=pyh9f0ad1d_0
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - queuelib=1.5.0=pyh9f0ad1d_0
  - requests=2.24.0=pyh9f0ad1d_0
  - rope=0.18.0=pyh9f0ad1d_0
  - rtree=0.9.4=py38h7ad75cc_1
  - scrapy=2.4.0=py38haa244fe_2
  - selenium=3.141.0=py38h1e8a9f7_1002
  - send2trash=1.5.0=py_0
  - service_identity=18.1.0=py_0
  - setuptools=49.6.0=py38h9bdc248_2
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - soupsieve=2.0.1=py_1
  - sphinx=3.3.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - spyder=4.1.5=py38h32f6830_0
  - spyder-kernels=1.9.4=py38h32f6830_0
  - sqlite=3.33.0=he774522_1
  - terminado=0.9.1=py38haa244fe_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=he774522_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py38h294d835_0
  - traitlets=5.0.5=py_0
  - twisted=20.3.0=py38h1e8a9f7_1
  - ujson=4.0.1=py38h7ae7562_1
  - update_checker=0.18.0=pyh9f0ad1d_0
  - urllib3=1.25.11=py_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - w3lib=1.22.0=pyh9f0ad1d_0
  - watchdog=0.10.3=py38h32f6830_2
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py38h32f6830_3
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - win_inet_pton=1.1.0=py38h32f6830_1
  - wincertstore=0.2=py38h32f6830_1005
  - winpty=0.4.3=4
  - wordcloud=1.8.0=py38h1e8a9f7_0
  - wrapt=1.11.2=py38h1e8a9f7_1
  - xlsxwriter=1.3.7=pyh9f0ad1d_0
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - yapf=0.30.0=pyh9f0ad1d_0
  - zeromq=4.3.2=ha925a31_4
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h62dcd97_1010
  - zope.interface=5.1.2=py38h1e8a9f7_1
  - zstd=1.4.5=h1f3a1b7_2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - wikipedia==1.4.0
prefix: D:\zTools\Anaconda3_x86_64\envs\webscrape
